const fs = require('fs');
const path = require('path');

const sharedAssetsDir = path.join(__dirname, '../../shared/assets/products');
const publicProductsDir = path.join(__dirname, '../public/products');
const outputFilePath = path.join(__dirname, '../src/data/generatedAssets.ts');

const folderToCategory = {
  'Accessories': 'accessories',
  'Bottoms & Joggers': 'bottoms',
  'Footwear': 'footwear',
  'Outerwear': 'outerwear',
  'Tops & Tees': 'tops'
};

function copyFolderSync(from, to) {
  if (!fs.existsSync(to)) {
    fs.mkdirSync(to, { recursive: true });
  }
  fs.readdirSync(from).forEach(element => {
    if (fs.statSync(path.join(from, element)).isDirectory()) {
      copyFolderSync(path.join(from, element), path.join(to, element));
    } else {
      fs.copyFileSync(path.join(from, element), path.join(to, element));
    }
  });
}

function syncAndScan() {
  const assetEntries = [];
  
  const pathsToTry = [
    sharedAssetsDir,
    path.join(__dirname, '../shared/assets/products'),
    path.join(process.cwd(), 'shared/assets/products'),
    path.join(process.cwd(), '../shared/assets/products'),
  ];

  let selectedSharedDir = '';
  for (const p of pathsToTry) {
    if (fs.existsSync(p)) {
      selectedSharedDir = p;
      break;
    }
  }

  if (!selectedSharedDir) {
    console.error('ERROR: Could not locate shared/assets/products directory in paths:', pathsToTry);
    process.exit(1);
  }

  console.log(`Syncing product assets from: ${selectedSharedDir}`);

  if (fs.existsSync(publicProductsDir)) {
    fs.rmSync(publicProductsDir, { recursive: true, force: true });
  }
  fs.mkdirSync(publicProductsDir, { recursive: true });

  const folders = fs.readdirSync(selectedSharedDir);
  folders.forEach((folder) => {
    const srcFolderPath = path.join(selectedSharedDir, folder);
    const destFolderPath = path.join(publicProductsDir, folder);
    
    if (fs.statSync(srcFolderPath).isDirectory()) {
      copyFolderSync(srcFolderPath, destFolderPath);

      const category = folderToCategory[folder] || folder.toLowerCase();
      const files = fs.readdirSync(srcFolderPath);
      files.forEach((file) => {
        if (file.toLowerCase().endsWith('.png')) {
          assetEntries.push({
            category,
            folder,
            filename: file
          });
        }
      });
    }
  });

  return assetEntries;
}

const entries = syncAndScan();

const content = `// This file is auto-generated at build/dev time by scripts/generate-assets.js.
// Do not edit this file manually.

export type AssetEntry = {
  category: 'outerwear' | 'tops' | 'bottoms' | 'footwear' | 'accessories';
  folder: string;
  filename: string;
};

export const ASSET_ENTRIES: AssetEntry[] = ${JSON.stringify(entries, null, 2)};
`;

fs.writeFileSync(outputFilePath, content, 'utf8');
console.log(`Successfully synced and generated ${entries.length} asset entries in ${outputFilePath}`);
