// This file is auto-generated at build/dev time by scripts/generate-assets.js.
// Do not edit this file manually.

export type AssetEntry = {
  category: 'outerwear' | 'tops' | 'bottoms' | 'footwear' | 'accessories';
  folder: string;
  filename: string;
};

export const ASSET_ENTRIES: AssetEntry[] = [
  {
    "category": "accessories",
    "folder": "Accessories",
    "filename": "AeroFit-Backpack-cover.png"
  },
  {
    "category": "accessories",
    "folder": "Accessories",
    "filename": "FlexGrip-Gym-Gloves-cover.png"
  },
  {
    "category": "accessories",
    "folder": "Accessories",
    "filename": "Motion-Wrist-Wraps-cover.png"
  },
  {
    "category": "accessories",
    "folder": "Accessories",
    "filename": "Titan-Steel-Water-Bottle-cover.png"
  },
  {
    "category": "accessories",
    "folder": "Accessories",
    "filename": "Velocity-Sports-Cap-cover.png"
  },
  {
    "category": "bottoms",
    "folder": "Bottoms & Joggers",
    "filename": "ActiveMotion-Sweatpants-cover.png"
  },
  {
    "category": "bottoms",
    "folder": "Bottoms & Joggers",
    "filename": "AeroRun-Shorts-cover.png"
  },
  {
    "category": "bottoms",
    "folder": "Bottoms & Joggers",
    "filename": "CoreFlex-Shorts-cover.png"
  },
  {
    "category": "bottoms",
    "folder": "Bottoms & Joggers",
    "filename": "TitanFit-Joggers-cover.png"
  },
  {
    "category": "bottoms",
    "folder": "Bottoms & Joggers",
    "filename": "Velocity-Training-Pants-cover.png"
  },
  {
    "category": "footwear",
    "folder": "Footwear",
    "filename": "AeroSprint-Runners-cover.png"
  },
  {
    "category": "footwear",
    "folder": "Footwear",
    "filename": "FlexRun-Pro-cover.png"
  },
  {
    "category": "footwear",
    "folder": "Footwear",
    "filename": "PowerStride-Shoes-cover.png"
  },
  {
    "category": "footwear",
    "folder": "Footwear",
    "filename": "TitanGrip-Trainers-cover.png"
  },
  {
    "category": "footwear",
    "folder": "Footwear",
    "filename": "Velocity-X-Sneakers-cover.png"
  },
  {
    "category": "outerwear",
    "folder": "Outerwear",
    "filename": "AeroFlex-Windbreaker-cover.png"
  },
  {
    "category": "outerwear",
    "folder": "Outerwear",
    "filename": "CoreMotion-Bomber-cover.png"
  },
  {
    "category": "outerwear",
    "folder": "Outerwear",
    "filename": "StormFitTrackJacket-cover.png"
  },
  {
    "category": "outerwear",
    "folder": "Outerwear",
    "filename": "Titan-Performance-Hoodie-cover.png"
  },
  {
    "category": "outerwear",
    "folder": "Outerwear",
    "filename": "Velocity-Zip-Jacket-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "Apex-Compression-Tee-Black-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "Apex-Compression-Tee-White-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "FlexCore-Tank-Top-Black-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "FlexCore-Tank-Top-White-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "MotionDry-Training-Shirt-Black-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "MotionDry-Training-Shirt-White-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "PrimeFit-Oversized-Tee-black-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "PrimeFit-Oversized-Tee-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "PrimeFit-Oversized-Tee-white-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "Velocity-Long-Sleeve-Black-cover.png"
  },
  {
    "category": "tops",
    "folder": "Tops & Tees",
    "filename": "Velocity-Long-Sleeve-White-cover.png"
  }
];
